# @author [Lucien Wright]
# @create date [01-13-2022]
# @desc [Automation - Backup Cisco Switches]

---
- hosts: cmiNet

  tasks:
   - name: backup config
     ios_command:
       commands: show run
     register: config

   - name: Save output to CMI Backup folder
     copy:
       content: "{{ config.stdout[0] }}"
      #  dest: /media/cmiNet/{{ ansible_net_hostname }}.txt
       dest: /etc/ansible/misc/{{ ansible_net_hostname }}.txt

- hosts: nxos

  tasks:
   - name: backup config
     nxos_command:
       commands: show run
     register: config

   - name: Save output to CMI Backup folder
     copy:
       content: "{{ config.stdout[0] }}"
       dest: /media/cmiNet/{{ ansible_net_hostname }}.txt

# Note:
# /media/cmiNet is mapped directly to our share drive backup folder at:
# \\192.168.50.202\IT Department\Network Administrator\Network Config Backups\CMI

#End of codes