# filename - ios_upgrade_second.yml
# @author [Lucien Wright]
# @create date [03-02-2024]
# @desc [Automation - Ansible Playbook to upgrade Cisco IOS]

---

# Ansible Playbook to upgrade Cisco IOS 

- hosts: cmiNet

  tasks:

## Copy software to target device 

   - name: Copy Image // This could take up to 4 minutes
     net_put: 
       src: "/media/netAdmin/tftp_netAdmin/c1000-universalk9-mz.152-7.E9.bin"
       dest: "flash:c1000-universalk9-mz.152-7.E9.bin"
     vars: 
       ansible_command_timeout: 600

## Change the Boot Variable to the new image 

   - name: Change Boot Variable to new image 
     ios_config: 
       commands: 
         - "boot system c1000-universalk9-mz.152-7.E9.bin"
       save_when: always 

## Reload the device 

   - name: Reload the Device 
     cli_command: 
       command: reload
       prompt: 
         - confirm
       answer: 
         - 'y'

## Wait for Reachability to the device 

   - name: Wait for device to come back online
     wait_for:
       host: "{{ inventory_hostname }}"
       port: 22     
       delay: 90
     delegate_to: localhost

## Check current image 

   - name: Check Image Version      
     ios_facts:

   - debug: 
       msg: 
       - "Current version is {{ ansible_net_version }}"

   - name: ASSERT THAT THE IOS VERSION IS CORRECT

     vars: 
       upgrade_ios_version: 15.2(7)E9

     assert:
       that:
         - upgrade_ios_version == ansible_net_version
   - debug: 
       msg: 
       - "Software Upgrade has been completed"
