---
- name: Palo Alto Playbook
  hosts: pa_2
  gather_facts: false
  connection: local

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: '10.176.90.12'
      api_key: LUFRPT1ZbndQMFZVNnY5a3FtdmhKTVBBKzZZNzVKWHM9dGd6WXg5MG82SHpvMEl3Y3BZdlBZcGdTaHFNVENnV0NhcnIybFlwUzIzaEsxQUJJRzFXaG1Fa2JOOGFLNzJXVA==

      #curl -k -X GET 'https://10.176.x.x/api/?type=keygen&user=<username>&password=<password>'

  tasks:
  
  - name: Get the system info
    panos_restart:
      provider: '{{ palo_provider }}'

