# @author [Lucien Wright]
# @create date [01-14-2022]
# @desc [Automation - Pull Info from Switches]

---
- name: Network Getting Started First Playbook
  hosts: cmiNet
  tasks:

    - name: Get config for IOS devices
      ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }} s/n is {{ ansible_net_serialnum }} model # is {{ ansible_net_model }}"

# Basically the same config as above but specifically for the Nexus switch(es)
# 

- name: Get info from Nexus
  hosts: nxos
  tasks:

    - name: Get config for NXOS devices
      nxos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

# ansible all -c network_cli -m ios_facts -e ansible_network_os=ios --vault-id ansadmin@/etc/ansible/passwd/pw1