# Include Command
# - name: Include Task - Remove Netflow Configuration
#   include_tasks: '{{ task_path }}/tk_remove_netflow.yml'

- name: Include Task - Get Device Info
  include_tasks: '{{ task_path }}/tk_get_device_info.yml'

- name: Netflow Configuration
  block:
    - name: Gather L2 Interfaces
      cisco.ios.ios_l2_interfaces:
        config:
        state: gathered
      register: l2_interfaces
      
    - name: Update Trunk Interfaces
      with_items: '{{ l2_interfaces["gathered"] }}'
      ios_config:
        lines: 
          - "no ip flow monitor NTAMONITOR input"
        parents: "interface {{ item.name }}"
      when: 'item["mode"] is defined and item["mode"] == "trunk"'

    - name: Remove Netflow Configuration
      ios_command:
        commands:
          - command: 'configure terminal'
          - command: 'no flow monitor NTAMONITOR'
          - command: 'no flow exporter NTAEXPORTER'
          - command: 'no flow record NTARECORD'

  when: netflow # Check to see if the netflow variable (set in device group_vars) is set to 'true'