---
# Netflow Variables
netflow: false
absolute_timestamp: false

# Notes: C1000 is not able to boot into INSTALL
# Staging Variables
install_cmd: "" # Install command for INSTALL
install_boot: "" # Boot statement for INSTALL
bundle_cmd: "" # For going to INSTALL from BUNDLE
bundle_boot: "boot system {{ dir }}:/{{ update_file }}" # Boot statement for BUNDLE
source: '{{ server_path }}\device' # Can be done in an all if we don't group anything by device

# Update File Variables - Last Updated 03/29/2025
version: "15.2(7)E11" # Version as shown on Device
update_file: "c1000-universalk9-mz.152-7.E11.bin" # Filename of the update file
md5: "9bca757bc8fbf1d46c67d2e2c9dec181" # Acquire from Cisco
update_kb: "16122" # File in kilobytes, divide bytes by 1024
