---
ansible_user: netadmin
ansible_network_os: ios
ansible_connection: network_cli
ansible_ssh_pass: "Kw@j1$C0LDandW3T!"

# Include secrets from vault
# If you need to include variables from vault.yml, use 'import_vars' or 'include_vars' in your playbook, not in group_vars.

# Path Variables
abs_path: '/etc/ansible' # Main path variable for referencing
task_path: '{{ abs_path }}/tasks' # Path variable for task location
playbook_path: '{{ abs_path }}/playbooks' # Path variable for playbook location
var_path: '{{ abs_path }}/vars' # Path variable for variable location
report_path: '/media/dotCom/reports' # Path variable for report location
server_path: '/media/dotCom' # Path variable to fileserver
tftp_path: '/media/netAdmin/tftp_netAdmin' # Path tftp server
ios_path: '/media/netAdmin/ciscoImages'
# config_path: '{{ abs_path }}/configurations' # Path variable for configuration location

# # Global Variables
null_vlan: '999'
management_interface: 'Vlan90'

# ## Netflow Variables
# netflow_server: '192.168.50.107'

## SNMP Variables
# snmp_auth: 'Gr33n0cean5@981'
# snmp_priv: 'VBNfPRIVl456$%^'
# snmp_read_group: 'snmp-v3-ReadOnly'
# snmp_write_group: 'snmp-v3-ReadWrite'
# snmp_read_view: 'snmp-v3-ReadOnly-View'
# snmp_write_view: 'snmp-v3-ReadWrite-View'
# snmp_read_user: 'snmp-read-user'
# snmp_write_user: 'snmp-write-user'