# filename: mp_set_enable_secret.yml
# @desc: Update enable secret password on all Cisco IOS devices
# @author: Lucien
# @run: ansible-playbook -i inventories/mysql_inventory.py playbooks/mp_set_enable_secret.yml

---
- name: Set enable secret password on Cisco switches
  hosts: all
  gather_facts: false
  connection: network_cli
  become: false
  collections:
    - cisco.ios

  vars:
    enable_secret_password: "{{ enable_pass }}"

  tasks:
    - name: Set enable secret password
      ios_config:
        lines:
          - enable secret {{ enable_secret_password }}
      when: enable_secret_password is defined
