# filename - pb_tacacs_update.yml
# @author [Lucien Wright]
# @create date [07-11-2025]
# @desc [Automation - Update AAA and TACACS+]
# Recommended run command: 
# ansible-playbook -i ./inventories/ --limit 'all' -f 40 ./playbooks/pb_tacacs_update.yml

---
- name: Configure Miscelaneous Configuration
  hosts: all    # or your specific group
  gather_facts: false
  connection: network_cli

  tasks:
    # - name: Apply fresh TACACS config
    #   template:
    #     src: templates/tacacs.j2
    #     dest: running-config
    #     save_when: always
  
    - name: Complete Micellaneous Configuration
      ios_config:               # for IOS and similar; use nxos_config for NX-OS
        #lines: "{{ lookup('template', 'aaa_radius.j2') | splitlines() }}"
        src: "{{ config_path }}/tacacs.j2"
        match: none
        replace: block
        
    - name: Include Task - Write Config
      include_tasks: '{{ task_path }}/tk_write_config.yml'